## Creating numpy array
use function np.array()

In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])

print(a)

[1 2 3 4 5 6 7 8 9]


In [6]:
l = []

for i in range(1,5):
  l.append(int(input("Enter : ")))

print(np.array(l))

Enter : 1
Enter : 2
Enter : 3
Enter : 4
[1 2 3 4]


### Dimensions in Arrays
Count the starting no of brackets
- 1-D Arrays [1 3 4]
- 2-D Arrays [[1 2 3 4 5],[1,2,3,55,1]]
- 3-D Arrays
- Higher dimensional Arrays

In [7]:
# to checl dimension of array

print(a.ndim)

1


In [9]:
# Creating 2 dimensional array

arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [5 6 7 8 9]]
2


In [12]:
# Creating 3 dimensional array

arr3 = np.array([[[1,2,3,4],[3,4,5,6],[2,7,1,9]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [2 7 1 9]]]
3


In [13]:
# creating n dimensional array with shorthand

arrn = np.array([1,2,3,4,5,6], ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]
10
