### Spacial Numpy Array :
- Array filled with 0's
- Array filled with 1's
- Create an empty array
- An array with range of elements
- Array with diagonal elements filled with 1's
- Create an array with values that are spaced linearly in specific interval


In [1]:
import numpy as np

## ZEROS

In [7]:
# One dimensional array with zeroes
arr_zeroes = np.zeros(10)
arr_zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# n dimensional array with zeros

arr_zero_2d = np.zeros((3, 4))
arr_zero_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ONES

In [11]:
# 1 dimensional array filled with 1

arr_one = np.ones(4)
arr_one

array([1., 1., 1., 1.])

In [12]:
# n dimensional array filled with 1

arr_ones_nd = np.ones((5, 5))
arr_ones_nd

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## EMPTY

In [13]:
# create 1 dimensional empty array

arr_empty = np.empty(4)
arr_empty

array([1., 1., 1., 1.])

In [14]:
# create n dimensional empty array

arr_empty_nd = np.empty((4, 3))
arr_empty_nd

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## RANGE

In [15]:
# 1 dimensional array with range

arr_range = np.arange(4)
arr_range

array([0, 1, 2, 3])

## DIAGONAL


In [21]:
# n x n array

arr_dia = np.eye(3)
arr_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# n x m array

arr_dia2 = np.eye(3, 5)
arr_dia2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## LINSPACE

In [32]:
arr_lin = np.linspace(0, 20, num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]
