## Numpy array with random numbers

In [ ]:
import numpy as np

### Rand()

Creates numbers between zero and one

In [27]:
# creating 1 dimensional array with random numbers between 0 and 1
my_var = np.random.rand(11)
print(my_var)

[0.18569874 0.7284205  0.68047376 0.59114091 0.82467114 0.79769098
 0.91612497 0.30958695 0.39109837 0.39789834 0.46929673]


In [65]:
# creating n dimensional array with random numbers between 0 and 1
my_var1 = np.random.rand(2, 5)
print(my_var1)

[[0.77770524 0.47266819 0.02012489 0.17660995 0.82132582]
 [0.44124314 0.25248708 0.08486086 0.08627951 0.88674428]]


### Randn()

generate random values close to zero, may reyturn positive or negative values

In [87]:
# creating 1 dimensional array 
arr_randn = np.random.randn(11)
print(arr_randn)

[-3.86803078e-01 -7.81983308e-01  9.52051043e-01 -1.98084339e-01
 -1.24334483e+00  1.64552751e-03  2.82003493e-01 -1.41236771e-01
  2.61849443e+00  6.16145763e-01 -4.49268874e-01]


In [95]:
# creating n dimensional array 
arr_randn_nd = np.random.randn(4, 3)
print(arr_randn_nd)

[[ 0.79272873 -0.18079496 -1.12289648]
 [-1.99822169 -0.88186816  0.73863017]
 [-0.73410929 -0.06037926  1.38283295]
 [ 1.76326763 -0.4536907   0.45524156]]


### Ranf()

- The function for doing random sampling in numpy
- It returns an array of specified shape and fills it with random floats in the half open interval

In [94]:
# creating 1 dimensional array 
arr_randf = np.random.ranf(11)
print(arr_randf)

[0.70032796 0.09466194 0.33163526 0.71964565 0.18109051 0.71574577
 0.4974598  0.20629026 0.70405382 0.70220336 0.70303064]


### Randint()

generate random values between a given range

In [165]:
# (min, max, total_numbers)

arr_randint = np.random.randint(1, 11, 5)
print(arr_randint)

[ 7  9  2 10 10]
