In [1]:
import numpy as np

## Arithmetic Functions

In [2]:
# creating 1 dimensional arrays


num_arr = np.array([1,2,6,33,2,6,8,10])

### max()

In [7]:
# Max

print(np.max(num_arr))

33


### argmax()

In [38]:
# argmax - position of max

print(np.argmax(num_arr))

3


### min()

In [8]:
# Min

print(np.min(num_arr))

1


### argmin()

In [40]:
# argmin : position of min

print(np.argmin(num_arr))

0


### axis

In [152]:
# axis 0 = row
# axis 1 = column
# by passing the axis, we can get mean for each axis 
print(np.min(num_arr , axis=0))

# TO GET THE Row of MIN
print(np.min([[1,3,99,5], [4,5,6,22]], axis=1))
print(np.min([[1,2,3,5], [4,2,2,2]], axis=0))

1
[1 4]
[1 2 2 2]


### mean()

In [15]:
# Mean

print(np.mean(num_arr))

8.5


### sqrt()

In [156]:
# Square root

print(np.sqrt(np.array([9, 25, 100, 64])))

[ 3.  5. 10.  8.]


### sin()

In [157]:
print(np.sin(num_arr))

[ 0.84147098  0.90929743 -0.2794155   0.99991186  0.90929743 -0.2794155
  0.98935825 -0.54402111]


### cumsum()

In [174]:
# we require it to find out median

print(np.cumsum(np.array([1,2,3,4])))

[ 1  3  6 10]
