In [1]:
import numpy as np

## Shape

In [16]:
num_arr_1d = np.array([1,2,3,4,5])
print(num_arr_1d.shape)

(5,)


In [60]:
num_arr_2d = np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(num_arr_2d.shape)

(2, 5)


In [76]:
num_arr_4d = np.array([[1,2,3,4,5], [5,6,7,8,9]], ndmin=4)
print(num_arr_4d.shape)

(1, 1, 2, 5)


## Reshape

In [102]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9])

x = my_arr.reshape(5, 2)

print(x)
print()
print(x.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

2


In [115]:
y = my_arr.reshape(2, 5, 1)

print(y)
print()
print(y.ndim)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]

3


In [141]:
one = x.reshape(-1)

print(one)
print()
print(one.ndim)

[0 1 2 3 4 5 6 7 8 9]

1
