In [1]:
import numpy as np

## Indexing

### 1-D

In [2]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [12]:
# Access elements by index in 1d

print(my_arr[3])

3


In [20]:
# Accessing last element


print(my_arr[-1])

10


### 2-D

In [34]:
mul_d_arr = np.array([[1,3],[2,5],[11,7]])

print(mul_d_arr)

[[ 1  3]
 [ 2  5]
 [11  7]]


In [46]:
# Accessing element at position row2 and column2

print(mul_d_arr[1][1])

5


In [39]:
# Accessing element at last position
print(mul_d_arr[-1][-1])

7


### 3-D

In [71]:
arr_3d = np.array([[[1,2],[6,7]]])
print(arr_3d)

[[[1 2]
  [6 7]]]


In [73]:
# Accessing element at second position
print(arr_3d[0][1][0])

6


## Slicing

In [103]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [105]:
z = np.array([[1,2,3,4,5], [9,8,7,6,5],[11,12,13,14,15]])

print(z)

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]


In [118]:
print(z[1, 1:])

[8 7 6 5]
