In [1]:
import numpy as np

## Iteration

### 1-D

In [19]:
# For one dimensional array

num_arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(num_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
for i in num_arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


### 2-D

In [16]:
# For 2 dimensional array

num_arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(num_arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
# NOT IDEAL

for i in num_arr_2d:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


### 3-D

In [17]:
# for 3 dimensional array

num_arr_3d = np.array([[[1,2,3,4],[5,6,7,8]]])

print(num_arr_3d)

[[[1 2 3 4]
  [5 6 7 8]]]


In [24]:
# NOT IDEAL

for i in num_arr_3d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


### np.nditer()

In [23]:
for i in np.nditer(num_arr_3d):
    print(i)

1
2
3
4
5
6
7
8


### nd.ndenumerate()

In [28]:


for i, data in np.ndenumerate(num_arr_3d):
    print(i, data)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
