In [1]:
import numpy as np

## Join Array:
- joining means putting contents of two or more arrays in single array

### 1-D

In [53]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,8,9,10,11])
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 7  8  9 10 11]


In [26]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[ 1  2  3  4  5  7  8  9 10]


### 2-D

In [38]:
arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[7,8],[9,10]])
print(arr1_2d)
print()
print(arr2_2d)

[[1 2]
 [3 4]]

[[ 7  8]
 [ 9 10]]


In [50]:
# By default it concatenate 2 arrays along axis 0

arr3_2d = np.concatenate((arr1_2d, arr2_2d))
print(arr3_2d)

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


In [49]:
# Concatenating 2 dimensional arrays along axis=1

arr3_2d = np.concatenate((arr1_2d, arr2_2d), axis=1)
print(arr3_2d)

[[ 1  2  7  8]
 [ 3  4  9 10]]


### stack()

In [51]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,8,9,10])
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 7  8  9 10]


In [56]:
# We will get a 2-D array here from two 1-D arrays

arr3 = np.stack((arr1, arr2), axis=1)

print(arr3)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [64]:
# We dont need to pass axis in below case

# Row
arr4 = np.hstack((arr1,arr2))
print(arr4)
print()

#Column
arr4 = np.vstack((arr1,arr2))
print(arr4)
print()

# Height
arr4 = np.dstack((arr1,arr2))

print(arr4)

[ 1  2  3  4  5  7  8  9 10 11]

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]

[[[ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]]]


## Split Array:
- Splitting breaks one array into multiple

### 1-D

In [65]:
a = np.array([1,2,3,4,5,6])

print(a)

[1 2 3 4 5 6]


In [74]:
# Split function takes array and no. of splits as argument

b = np.split(a, 3)

for arr in b:
    print(arr)
    print()

[1 2]

[3 4]

[5 6]



### 2-D

In [80]:
# Create 2d array

x = np.array([[1,2],[3,4],[5,6]])

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [81]:
y = np.split(x, 3)

for arr in y:
    print(arr)
    print()

[[1 2]]

[[3 4]]

[[5 6]]



Split along the axes

In [83]:
z = np.split(x, 2, axis=1)

for arr in b:
    print(arr)
    print()

[[1 2]]

[[3 4]]

[[5 6]]

