In [1]:
import numpy as np

## Search
- Search an array for a certain value and return the index that get a match

In [19]:
num_arr = np.array([1,2,3,4,5,6,7,8,9,11,23,40,20,6,1])
                  # 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
print(num_arr)

[ 1  2  3  4  5  6  7  8  9 11 23 40 20  6  1]


In [34]:
# Lets search for 23 in an array

x = np.where(num_arr == 6)

print(x)

print(np.where(num_arr % 2 == 0))

(array([ 5, 13], dtype=int64),)
(array([ 1,  3,  5,  7, 11, 12, 13], dtype=int64),)


## Sort
- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending

### 1-D Array

In [71]:
num_unsorted = np.array([44,2,7,4,1,9,11,65,12,15,42,7])

print(f"Unsorted : {num_unsorted}")

num_sorted = np.sort(num_unsorted)

print(f"Sorted : {num_sorted}")

Unsorted : [44  2  7  4  1  9 11 65 12 15 42  7]
Sorted : [ 1  2  4  7  7  9 11 12 15 42 44 65]


### 2-D Array

In [100]:
num_unsorted = np.array([[44,2,7],[4,1,9],[11,65,12],[15,42,7]])

print(f"Unsorted : {num_unsorted}")
num_sorted = np.sort(num_unsorted, axis=0)
print()


print(f"Sorted : {num_sorted}")

Unsorted : [[44  2  7]
 [ 4  1  9]
 [11 65 12]
 [15 42  7]]

Sorted : [[ 4  1  7]
 [11  2  7]
 [15 42  9]
 [44 65 12]]


## Search Sorted
- Performs binary search in the array and returns the index where the specified value would be inserted to maintain the search order

In [69]:
x = np.array([1,2,3,6,7,8,9,10])

x1 = np.searchsorted(x, 4, side="right")

print(x1)
# print(x)

x2 = np.searchsorted(x, [4,5,6], side="right")

print(x2)

3
[3 3 4]


## Filter
- Getting some elements out of an existing array and creating a new array outn of them

In [101]:
print(num_arr)

[ 1  2  3  4  5  6  7  8  9 11 23 40 20  6  1]


In [113]:
filters = [True, False, True,True, False, True,True, False, True,True, False, True,True, False, True]

new_arr = num_arr[filters]


print(new_arr)

[ 1  3  4  6  7  9 11 40 20  1]
