In [ ]:
import numpy as np

In [116]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


## Insert

In [12]:
# first argument is arr, second : index or indexes, third : number to be inserted

np.insert(x, 1, 14)

array([ 0, 14,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
# first argument is arr, second : index or indexes, third : number to be inserted

np.insert(x, (2,4), 10)

array([ 0,  1, 10,  2,  3, 10,  4,  5,  6,  7,  8,  9])

### 2-D

In [41]:
y = np.array([[1,2,3,4],[5,6,7,8]])


np.insert(y, (2,4), 99)

array([ 1,  2, 99,  3,  4, 99,  5,  6,  7,  8])

## Append

In [51]:
np.append(y, [1,2,3,4])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

### 2-D

In [107]:
z = np.array([[1,2,3,4],[5,6,7,8]])


l = np.append(z, [[11,22,33,44]], axis=0)
print(l)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]


## delete:

In [129]:
delt = np.arange(2, 10)
print(delt)

[2 3 4 5 6 7 8 9]


In [135]:
np.delete(delt, 5)

array([2, 3, 4, 5, 6, 8, 9])